# This workflow enables auto-merge for automated pull requests. This requires
# that the pull request is labeled with 'automerge' and the author is 'github-actions[bot]'.
# This enables the auto-merge functionality, but branch protection rules MUST be satisfied
# in order for the auto-merge to be performed.

name: Enable Auto-Merge for Relevant PRs

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'automerge' &&
      github.event.pull_request.user.login == 'github-actions[bot]'

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge for the pull request
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
